### ISSUE TITLE
Failure when running a new React Web App

### ISSUE THREAD

**Issue by Fanneyyy** [hgop/syllabus-2020#2]
# Expected Behaviour
After creating a new React web application it should run after installing all dependencies and running `npm start`.

# Current Behaviour
After running `npm start` I get a TypeError: `TypeError: Cannot assign to read only property 'jsx' of object '#<Object>’`.

## Context

* Operating System: MacOS Catalina
* npm --version: 6.13.4
* create-react-app --version: 4.0.0

# Failure Information 

## Steps to Reproduce
1. `npm install -g create-react-app`
2. `create-react-app connect-four --template typescript`
3. cd connect-four
4. npm install
5. npm start

## Failure Logs

```
> connect-four-client@0.1.0 start /Users/fanney/hgop_2020/connect-four-client-solution
> react-scripts start

/Users/fanney/hgop_2020/connect-four-client-solution/node_modules/react-scripts/scripts/utils/verifyTypeScriptSetup.js:239
      appTsConfig.compilerOptions[option] = value;
                                          ^

TypeError: Cannot assign to read only property 'jsx' of object '#<Object>'
    at verifyTypeScriptSetup (/Users/fanney/hgop_2020/connect-four-client-solution/node_modules/react-scripts/scripts/utils/verifyTypeScriptSetup.js:239:43)
    at Object.<anonymous> (/Users/fanney/hgop_2020/connect-four-client-solution/node_modules/react-scripts/scripts/start.js:31:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! connect-four-client@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the connect-four-client@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/fanney/.npm/_logs/2020-11-20T15_10_45_846Z-debug.log

```

**Comment by Fanneyyy** [comment]
This error seems to present itself in the latest Typescript version. Downgrading the version, i.e. remove semver ^ to force npm to use typescript version 4.0.5, should work:
`package.json`
~~~
{
  "name": "connect-four",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    …
    "typescript": "4.0.5",
    …
   },
   …
}
~~~
There’s also a minor change needed in the Typescript config, like so:
`tsconfig.json`
~~~
{
  "compilerOptions": {
    …
    "jsx": "react"
  },
  …
}
~~~

After making the change make sure to delete `package-lock.json` and `node_modules` and install the dependencies fresh:
```
rm package-lock.json
rm -rf node_modules
npm install
npm start
```
