### ISSUE TITLE
MicroK8s - File system watcher limit

### ISSUE THREAD

**Issue by soring** [hgop/syllabus-2020#43]
# Expected Behaviour
Pods on MicroK8s should run correctly

# Current Behaviour
Pods are exiting with an error that a limit for the number of file system watchers has been reached

## Context
Ubuntu instances we are using have a file system watcher limit of 8192
```Bash
$ sysctl fs.inotify.max_user_watches
fs.inotify.max_user_watches = 8192
```

* Operating System:
```Bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```

# Failure Information (for bugs)
This is not a bug, but a feature. A feature that needs to be configured.

## Steps to Reproduce

Once you've created enough pods in the cluster you will run out of these file watchers and get this error. It might be different in Python, I got my error running the connect4 client. 

## Failure Logs

```
Starting the development server...

node:events:306
      throw er; // Unhandled 'error' event
      ^

Error: ENOSPC: System limit for number of file watchers reached, watch '/app/public'
    at FSWatcher.<computed> (node:internal/fs/watchers:218:26)
    at Object.watch (node:fs:1550:34)
    at createFsWatchInstance (/app/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:38:15)
    at setFsWatchListener (/app/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:81:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/app/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:233:14)
    at FSWatcher.NodeFsHandler._handleDir (/app/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:429:19)
    at FSWatcher.<anonymous> (/app/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:477:19)
    at FSWatcher.<anonymous> (/app/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:482:16)
    at FSReqCallback.oncomplete (node:fs:192:5)
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError (/app/node_modules/webpack-dev-server/node_modules/chokidar/index.js:260:10)
    at createFsWatchInstance (/app/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:40:5)
    at setFsWatchListener (/app/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:81:15)
    [... lines matching original stack trace ...]
    at FSReqCallback.oncomplete (node:fs:192:5) {

```

## Workaround or Fix
SSH into the ubuntu server running your MicroK8s server, run the following
``` Bash
sysctl fs.inotify.max_user_watches 
# output: fs.inotify.max_user_watches = 8192
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf
# output: fs.inotify.max_user_watches=524288
sysctl fs.inotify.max_user_watches
# output: fs.inotify.max_user_watches = 524288
```
Workaround and solution was found here https://github.com/awslabs/amazon-eks-ami/issues/501

**Comment by magnsve** [comment]
Nice! Can confirm that this works.
